version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: youtube
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/youtube
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY:-YOUR_API_KEY}
      YOUTUBE_SEARCH_QUERY: ${YOUTUBE_SEARCH_QUERY:-news}
      YOUTUBE_FETCH_INTERVAL: ${YOUTUBE_FETCH_INTERVAL:-10}
    ports:
      - "8000:8000"
    restart: always

volumes:
  postgres_data:
